name: build
on: [push] 

# NOTE: 3.12 has problems with numba so I am including it in the list

jobs:

  build-cpython:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.9' , '3.10', '3.11' ]
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3    
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - shell: bash
      name: install requirements 
      run: |
           set -ex
           python -m pip install -q -r requirements.pip.txt -r requirements.txt
           which python 
    - shell: bash
      name: run tests
      run: python -u ./run_tests.py
    - uses: actions/upload-artifact@v4
      name: upload artifacts
      with:
        name: conda-${{ matrix.os }}-${{ matrix.python-version }}
        retention-days: 5
        path: |
              ./examples/**/*.html
              ./*.log
           

  build-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ] 
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3  
    - uses: mamba-org/setup-micromamba@v1
      name: setup conda
      with:
        environment-name: my-env
        create-args: -c bokeh -c conda-forge python=${{ matrix.python-version }} --file requirements.conda.txt --file requirements.txt
    - shell: bash -el {0}
      name: run tests
      run: python -u ./run_tests.py
    - uses: actions/upload-artifact@v4
      with:
        name: conda-${{ matrix.os }}-${{ matrix.python-version }}
        retention-days: 5
        path: |
              ./examples/**/*.html
              ./*.log










