name: test
on: [push] 

# NOTE: 3.12 has problems with numba so I am including it in the list

jobs:

  build-cpython:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.9' , '3.10', '3.11' ]
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2    
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - shell: bash
      run: |
           set -ex
           python -m pip install  -r requirements.pip.txt -r requirements.txt

  build-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ] 
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2   
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channel-priority: true
        activate-environment: my-env
    - shell: bash -el {0}
      run: |
           set -ex
           mamba install -y -c bokeh -c conda-forge python=${{ matrix.python-version }} --file requirements.conda.txt --file requirements.txt











